[ENHANCEMENT] - Project template
betrybe/content-templates pull request #1
Opened 2020-05-05 01:26 UTC by Caciquez

Me, @tuliostarling , and @LeandroLM had the idea of ​​creating templates for live lectures, content and projects.

The point is to external producers have a skeleton to follow when creating the next materials, which will be consumed by students, using the templates.

The templates will work as guidelines of good practices of making markdowns contents also.

2020-05-20 16:52 UTC, jeanpsv requested changes

2020-05-20 16:52 UTC, jeanpsv commented on README.md
> +Você já usa o GitHub diariamente para desenvolver os exercícios, certo? Agora, para desenvolver os projetos, você deverá seguir as instruções a seguir. Fique atento a cada passo, e se tiver qualquer
```suggestion
Você já usa o GitHub diariamente para desenvolver os exercícios, certo? Agora, para desenvolver os projetos, você deverá seguir as instruções a seguir. Tenha atenção a cada passo, e se tiver qualquer dúvida, nos envie por Slack! #vqv 🚀
```

2020-05-20 16:52 UTC, jeanpsv commented on README.md
> +Aqui você vai encontrar os detalhes de como estruturar o desenvolvimento do seu projeto a partir deste repositório, utilizando uma branch específica e um Pull Request para colocar seuscódigos.
```suggestion
Aqui você vai encontrar os detalhes de como estruturar o desenvolvimento do seu projeto a partir deste repositório, utilizando uma _branch_ específica e um _Pull Request_ para colocar seus códigos.
```

2020-05-20 16:52 UTC, jeanpsv commented on README.md
> +## Oque deverá ser deenvolvido
```suggestion
## Oque deverá ser desenvolvido
```

2020-05-20 16:52 UTC, jeanpsv commented on README.md
> +  * Vá até a página de _Pull Requests_ do [repositório no GitHub](https://github.com/tryber/sd-0x-block7-project-daily-prophet/pulls)
```suggestion
  * Vá até a página de _Pull Requests_ do [repositório no GitHub](https://github.com/tryber/sd-0x-blockx-[project-name]/pulls)
```

2020-05-20 16:52 UTC, jeanpsv commented on README.md
> +  * Volte até a [página de _Pull Requests_ do repositório](https://github.com/tryber/sd-0x-block7-project-daily-prophet/pulls) e confira que o seu _Pull Request_ está criado
```suggestion
  * Volte até a [página de _Pull Requests_ do repositório](https://github.com/tryber/sd-0x-blockx-[project-name]/pulls) e confira que o seu _Pull Request_ está criado
```

2020-05-20 16:52 UTC, jeanpsv commented on README.md
> +À medida que você e os outros alunos forem entregando os projetos, vocês serão alertados **via Slack** para também fazer a revisão dos _Pull Requests_ dos seus colegas. Fiquem atentos às mensagens do
```suggestion
À medida que você e as outras pessoas que estudam na Trybe forem entregando os projetos, vocês receberão um alerta **via Slack** para também fazer a revisão dos _Pull Requests_ dos seus colegas. Atentem-se às mensagens do _"Pull Reminders"_ no _Slack_!
```

2020-05-25 10:13 UTC, jeanpsv requested changes

2020-05-25 10:13 UTC, jeanpsv commented on project/project_rubric_template.md
> +Todo aluno deve fazer uma _Pull Request_ para o repositório do modelo deste projeto _(onde está o guia para a entrega do projeto)_.
```suggestion
Todo estudante deve fazer uma _Pull Request_ para o repositório do modelo deste projeto _(onde está o guia para a entrega do projeto)_.
```

2020-05-25 10:13 UTC, jeanpsv commented on project/project_rubric_template.md
> +Você deve avaliar o aluno para cada um dos itens obrigatórios e de bônus da especificação em relação às seguintes regras.
```suggestion
Você deve avaliar o estudante para cada um dos itens obrigatórios e de bônus da especificação em relação às seguintes regras.
```

2020-05-25 10:13 UTC, jeanpsv commented on project/project_rubric_template.md
> +Para cada aluno, você deve preencher sua avaliação na planilha dentro da pasta do aluno. Todo projeto semanal deve ter uma aba diferente na planilha.
```suggestion
Para cada estudante, você deve preencher sua avaliação na planilha dentro da pasta do estudante. Todo projeto semanal deve ter uma aba diferente na planilha.
```

2020-05-26 15:50 UTC, jeanpsv requested changes

2020-05-26 15:50 UTC, jeanpsv commented on project/project_rubric_template.md
> +### O aluno deve criar uma [intenção do projeto] de maneira a cumprir os seguintes requisitos.
```suggestion
### O estudante deve criar uma [intenção do projeto] de maneira a cumprir os seguintes requisitos.
```

2020-05-26 15:50 UTC, jeanpsv commented on project/project_rubric_template.md
> +Abaixo estão as habilidades que concordamos em ensinar ao aluno na block X. Usaremos essas habilidades para vincular o conhecimento adquirido durante a semana aos requisitos do projeto.
```suggestion
Abaixo estão as habilidades que concordamos em ensinar ao estudante na block X. Usaremos essas habilidades para vincular o conhecimento adquirido durante a semana aos requisitos do projeto.
```

2020-05-26 15:50 UTC, jeanpsv commented on project/project_rubric_template.md
> +Procure na unidade compartilhada "LEARNING" uma pasta. Dentro dela, você encontrará uma pasta para o grupo específico que está avaliando. Dentro desta pasta deve haver uma pasta `* Estudantes`. Deve
```suggestion
Procure na unidade compartilhada "LEARNING" uma pasta. Dentro dela, você encontrará uma pasta para o grupo específico que está avaliando. Dentro desta pasta deve haver uma pasta `* Estudantes`. Deve haver uma pasta para cada estudante e dentro dela uma planilha para as avaliações semanais.
```

2020-06-10 01:35 UTC, antoniosb commented
@Caciquez @LeandroLM @tuliostarling @albertosca isso não ficaria melhor no playbook de conteúdo ?

2020-06-10 01:44 UTC, Caciquez commented
A ideia era de ficar esse repositorio de template, para replicar quando for criar um novo projet odo zero e ja ter o esqueleto!

No caso no PR que eu estou fazendo pro playbook de artilharia ta documentado melhor como usar e o @jeanpsv está usando no playbook de automatizaçao também

Acha que vale colocar no playbook de contéudo a mais também ou centralizar em apenas 1 playbook @antoniosb ?

2020-06-12 14:13 UTC, albertosca commented
Eu acho a idéia de ter tudo aqui num esqueleto boa! Com o playbook linkando pra cá. Inclusive redescobri esse PR quando vim pra esse repositório colocar um README pra linkar no playbook. 

@Caciquez Acho que vale, também, deixar a referência do README alinhada com os mais novos que temos usados, como [esse do meme generator](https://github.com/betrybe/sd-0x-block5-project-meme-generator/blob/master/README.md). Que que vc acha?

2020-06-12 22:51 UTC, Caciquez commented
Acho uma boa @albertosca vou dar uma refatorada, e alinhar com as docs no Playbook de artilharia!

2020-06-15 13:20 UTC, albertosca approved these changes
👌

2020-06-15 13:20 UTC, albertosca commented on project/project_template.md
> +### DEPOIS DE TERMINAR O DESENVOLVIMENTO
```suggestion
### DEPOIS DE TERMINAR O DESENVOLVIMENTO (OPCIONAL)
```

2020-06-15 17:03 UTC, jeanpsv approved these changes

2020-06-15 17:17 UTC, merged